name: first

on:
  workflow_dispatch:
  schedule:
    - cron: '7 * * * *'

jobs:
  just-echo-time:
    runs-on: ubuntu-latest
    steps:
      - name: First test
        run: date
      - name: My Curl Test
        run: curl http://joekinley.org
